name: Release

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    
    strategy:
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: 'csharp'
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: |
          5.0.x
          6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore /p:UseSharedCompilation=false
    - name: Test
      env:
        OPT_ACCOUNT_ADDRESS: ${{ secrets.OPT_ACCOUNT_ADDRESS }}
        OPT_ACCOUNT_EMAIL: ${{ secrets.OPT_ACCOUNT_EMAIL }}
        OPT_ACCOUNT_NAME: ${{ secrets.OPT_ACCOUNT_NAME }}
        OPT_ACCOUNT_PASSWORD: ${{ secrets.OPT_ACCOUNT_PASSWORD }}
        OPT_ACCOUNT_SECRET_KEY: ${{ secrets.OPT_ACCOUNT_SECRET_KEY }}
        OPT_TEST_USER_CREATE: ${{ secrets.OPT_TEST_USER_CREATE }}
        OPT_TEST_USER_EMAIL: ${{ secrets.OPT_TEST_USER_EMAIL }}
      run: dotnet test --no-build --verbosity normal
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2     
